// <auto-generated />
namespace BusWebAPI.DAL.Implementation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class busnumberofseats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(busnumberofseats));
        
        string IMigrationMetadata.Id
        {
            get { return "201907041716439_bus-numberofseats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
